<?php
$title = 'Tableau de bord | My Quizz App';
$this->headTitle ( $title );
?>
<?php

echo $this->headLink ()
->prependStylesheet ( $this->basePath ( 'css/perso.css' ) )
->prependStylesheet ( $this->basePath ( 'ressources_bo_webapp/css/style.css' ) )
->prependStylesheet ( $this->basePath ( 'css/gallery.css' ) )
->prependStylesheet ( $this->basePath ( 'ressources_bo_webapp/css/style-responsive.css' ) )
->prependStylesheet ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css' ) );
?>
 	<section id="container" class="">
      
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">
              <!-- page start-->
              <div class="row">
                  <aside class="profile-nav col-lg-3">
                      <section class="panel">
                          <div class="user-heading round">
                              <a href="#">
                                  <img src="img/profile-avatar.jpg" alt="">
                              </a>
                              <h1>Jonathan Smith</h1>
                              <p>jsmith@flatlab.com</p>
                          </div>

                          <ul class="nav nav-pills nav-stacked">
                              <li class="active"><a href="profile.html"> <i class="fa fa-user"></i> Profile</a></li>
                              <li><a href="profile-activity.html"> <i class="fa fa-calendar"></i> Recent Activity <span class="label label-danger pull-right r-activity">9</span></a></li>
                              <li><a href="profile-edit.html"> <i class="fa fa-edit"></i> Edit profile</a></li>
                          </ul>

                      </section>
                  </aside>
                  <aside class="profile-info col-lg-6">
                      <section class="panel">
                          <form>
                              <textarea placeholder="Whats in your mind today?" rows="2" class="form-control input-lg p-text-area"></textarea>
                          </form>
                          <footer class="panel-footer">
                              <button class="btn btn-danger pull-right">Post</button>
                              <ul class="nav nav-pills">
                                  <li>
                                      <a href="#"><i class="fa fa-map-marker"></i></a>
                                  </li>
                                  <li>
                                      <a href="#"><i class="fa fa-camera"></i></a>
                                  </li>
                                  <li>
                                      <a href="#"><i class=" fa fa-film"></i></a>
                                  </li>
                                  <li>
                                      <a href="#"><i class="fa fa-microphone"></i></a>
                                  </li>
                              </ul>
                          </footer>
                      </section>
                      <section class="panel">
                    <!--      <div class="bio-graph-heading">
                              Aliquam ac magna metus. Nam sed arcu non tellus fringilla fringilla ut vel ispum. Aliquam ac magna metus.
                          </div>-->
                          <div class="panel-body bio-graph-info">
                              <h1>Bio Graph</h1>
                              <div class="row">
                                  <div class="bio-row">
                                      <p><span>First Name </span>: Jonathan</p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Last Name </span>: Smith</p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Country </span>: Australia</p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Birthday</span>: 13 July 1983</p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Occupation </span>: UI Designer</p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Email </span>: jsmith@flatlab.com</p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Mobile </span>: (12) 03 4567890</p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Phone </span>: 88 (02) 123456</p>
                                  </div>
                              </div>
                          </div>
                      </section>
                      <section>
                          <div class="row">
                              <div class="col-lg-12">
                                  <div class="panel">
                                    <div class="panel-body"  style="border-left: 5px solid #ff766c;" >
										<ul class="grid cs-style-3">
											<figure>
												<img src="img/1.jpg" alt="img04" style="width:100%;height:100%">
												<figcaption>
													<h3>Mindblowing</h3>
													<span>lorem ipsume </span>
													<a class="fancybox" rel="group" href="img/1.jpg">Take a look</a>
												</figcaption>
											</figure>
										</ul>
									</div>
								</div><div class="panel">
									<div class="panel-body"   style="border-left: 5px solid #dd766c;">
										<ul class="grid cs-style-3">
											<figure>
												<img src="img/1.jpg" alt="img04" style="width:100%;height:100%">
												<figcaption>
													<h3>Mindblowing</h3>
													<span>lorem ipsume </span>
													<a class="fancybox" rel="group" href="img/1.jpg">Take a look</a>
												</figcaption>
											</figure>
										</ul>
										</div>
										<div class="panel-body"   style="border-left: 5px solid #cc766c;">
										<ul class="grid cs-style-3">
											<figure>
												<img src="img/1.jpg" alt="img04" style="width:100%;height:100%">
												<figcaption>
													<h3>Mindblowing</h3>
													<span>lorem ipsume </span>
													<a class="fancybox" rel="group" href="img/1.jpg">Take a look</a>
												</figcaption>
											</figure>
										</ul>
										</div>
										<div class="panel-body"   style="border-left: 5px solid #aa766c;">
										<ul class="grid cs-style-3">
											<figure>
												<img src="img/1.jpg" alt="img04" style="width:100%;height:100%">
												<figcaption>
													<h3>Mindblowing</h3>
													<span>lorem ipsume </span>
													<a class="fancybox" rel="group" href="img/1.jpg">Take a look</a>
												</figcaption>
											</figure>
										</ul>
                                    </div>
                                  </div>
                              </div>
                              
                          </div>
                      </section>
                  </aside>
              </div>

              <!-- page end-->
          </section>
      </section>
      <!--main content end-->
  </section>

<?php
echo $this->headScript ()
//->prependFile ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/bootstrap-modal/js/bootstrap-modal.js' ) )
//->prependFile ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js' ) )
//->prependFile ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/bootstrap-toastr/toastr.min.js' ) )
//->prependFile ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/bootbox/bootbox.min.js' ) )
//->prependFile ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js' ) )
//->prependFile ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js' ) )
//->prependFile ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/select2/select2.min.js' ) )
//->prependFile ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js' ) )
->prependFile ( $this->basePath ( 'js/modernizr.custom.js' ) )
//->prependFile ( $this->basePath ( 'ressources_bo_webapp/assets/global/plugins/jquery-validation/js/jquery.validate.min.js' ) )
;
?>
<script type="text/javascript">

var table = $('#datatable_users');
$(document).ready(function() {
	
	
/* 	table.dataTable({
	
	 	"language": {
	 		"processing":"Traitement en cours...",
	 		"loadingRecords": "<i class='fa fa-spinner fa-spin'></i> Chargement en cours...",
	            "aria": {
	                "sortAscending": ": activer pour trier la colonne par ordre croissant",
	                "sortDescending": ": activer pour trier la colonne par ordre d&eacute;croissant"
	            },
	            "emptyTable": "Aucune donn&eacute;e disponible dans le tableau",
	            "info": "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
	            "infoEmpty": "Affichage de l'&eacute;l&eacute;ment 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
	            "infoFiltered": "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
	            "infoPostFix":    "",
	            "lengthMenu": "Afficher _MENU_ &eacute;l&eacute;ments",
	            "search": "Filtrer&nbsp;:",
	            "zeroRecords": "Aucun &eacute;l&eacute;ment &agrave; afficher",
	            "paginate": {
	                "previous":"Pr&eacute;c&eacute;dent",
	                "next": "Suivant",
	                "last": "Dernier",
	                "first": "Premier"
	            }
	    },
//	    "ajax": {
//			  "url": "/users_datatable/?= $_SESSION["user"]["idAdmin"] ?>", 
//			},
	    "bStateSave": false, // save datatable state(pagination, sort, etc) in cookie.
		"ordering": true,
	    "lengthMenu": [
	        [5, 10, 15, 20, -1],
	        [5, 10, 15, 20, "All"] // change per page values here
	    ],
	    // set the initial value
	    "pageLength": 10,
	    "columnDefs": [{  // set default column settings
	        'orderable': false,
	        'targets': [0]
	    }, {
	        "searchable": false,
	        "targets": [0]
	    }],
	    "order": [
	        [1, "desc"]
	    ]
	});
 */
// 	$('#datatable_users tbody td img').live('click', function() {
// 	    $("#datatable_users td.details").each(function(i, o){
// 	        $trParent = $(o).parents()[0];
// 	        $("#datatable_users tbody td img").attr("src", "/ressources_bo_webapp/assets/global/plugins/datatables/examples/resources/details_open.png");
// 	        $trParent.remove();
	        
// 	    });
// 	    var nTr = $(this).parents('tr')[0];
// 	    if (table.fnIsOpen(nTr))
// 	    {
// 	        /* This row is already open - close it */
// 	        this.src = "/ressources_bo_webapp/assets/global/plugins/datatables/examples/resources/details_open.png";
// 	        table.fnClose(nTr);
// 	    }
// 	    else
// 	    {
// 	        /* Open this row */
// 	        this.src = "/ressources_bo_webapp/assets/global/plugins/datatables/examples/resources/details_close.png";
// 	        table.fnOpen(nTr, fnFormatDetails(table, nTr), 'details');
// 	        var aData = table.fnGetData(nTr);
// 	        var id = aData[2];
// 	        console.log($(this).attr('data-id'));
// 	        id=$(this).attr('data-id');
// 	        $.ajax({
// 		        method:"get", 
// 		        url:'/quizz_form/'+id+'/U', 
// 		        success:function(data){ table.fnOpen(nTr, data, 'details');}, 
// 		        error:function(){ table.fnOpen(nTr, $("#divErrorGrabDataMessage").html(), 'details');}
// 		    });
// 	    }
// 	});
// 	$('.details').click(function(){
// 		alert($(this).attr('data-id'));
// 	});
// 	var nCloneTh = document.createElement('th');
//     var nCloneTd = document.createElement('td');
//     nCloneTd.innerHTML = '<img src="img/zf2-logo.png">';
//     nCloneTd.className = "center";

//     $('#datatable_users thead tr').each(function() {
//         this.insertBefore(nCloneTh, this.childNodes[0]);
//     });

//     $('#datatable_users tbody tr').each(function() {
//         this.insertBefore(nCloneTd.cloneNode(true), this.childNodes[0]);
//     });
});

 function showDetails(idUser){
// 	//alert(idTest);
// 	//$('#details').html('<p>'+idUser+'</p>');
	
	$.ajax({
	        url: '/quizz_form/'+idUser+'/U',
	        success: function(response) {
	        	$('#full_modal_details').html(response);
	        	$('#full_modal_details').modal('show');
	        	//$modal.html(response);
	        	// $('#modal_transmission').modal('show');
	        }
	 });
 }
 function showQuestionDetails(idTest){
//	 	alert(idTest);
//	 	//$('#details').html('<p>'+idUser+'</p>');
		
	 	$.ajax({
	 	        url: '/quizz_form/'+idTest+'/R',
	 	        success: function(response) {
	 	        	$('#responseDetails').html(response);
	 	        	//$('#full_modal_details').modal('show');
	 	        	//$modal.html(response);
	 	        	// $('#modal_transmission').modal('show');
	 	        }
	 	 });
	 }
 function fnFormatDetails(oTable, nTr)
 {
     var aData = oTable.fnGetData(nTr);
     var id = aData[2];
     var sOut = '<div id="divDetailAjax-' + id + '"><i style="font-size:20px;" class="fa fa-spinner fa-spin"></i> ' 
             + ' &nbsp;Chargement en cours...</div>';

     return sOut;
 }
 /**
  * Export Excel
  */
  function dataExport(){
 	 							//<input type="hidden" value="export=true&filtre=bloquer" id="dataexport" />
 	var filtre = "export=true";//pour le moment null après il sera la valeur de l'input $('#dataexport').val();
 	$('#spinner-export').html("<i style='font-size:15px;' class='fa fa-spinner fa-spin'>");
 	//alert();
 	$.ajax({
 		type : "POST",
 		dataType: 'json',
 		data : filtre,
 		url : "/Q_Statistic/<?= $_SESSION["user"]["idAdmin"] ?>",
 		 success : function(response){
 		 	$('#spinner-export').html('');
 		 },
 		 error : function(){
 		 	$('#spinner-export').html('');
 		 }
 	})
 	.done(function(data){
 	    var $a = $("<a>");
 	    $a.attr("href",data.file);
 	    $("body").append($a);
 	    $a.attr("download","export-utilisateurs.xls");
 	    $a[0].click();
 	    $a.remove();
 	});
 		
 }
</script>